name: ci

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: restore tools
        run: dotnet tool restore
      
      - name: get version
        run: |
          echo "semantic_version=$(dotnet nbgv get-version -v AssemblyInformationalVersion)" >> $GITHUB_ENV
      
      - run: echo "semantic version is ${{ env.semantic_version }}"
        name: "version: ${{ env.semantic_version }}"
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src/Scraper
          file: ./src/Scraper/Dockerfile
          push: true
          tags: staff0rd/bags:latest
          build-args: |
            VERSION=${{ env.semantic_version }}